---
- name: install some package
  package: 
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    - wget
    - yum-utils
    - git
    - python3
    - python3-pip
    - lvm2
    - device-mapper-persistent-data
    - dnf-plugins-core

- name: add docker repository
  yum_repository:
    name: docker
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    description: Docker CE Stable Repository
    enabled: yes

- name: add gpg key
  rpm_key:
    key: https//download.docker.com/linux/centos/gpg
    state: present

- name: install docker
  package: 
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest

- name: start docker
  service:
    name: docker
    state: started
    enabled: yes

- name: install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  notify: restart docker

- name: installe docker python package
  pip:
    name: docker-py
    state: present
    executable: pip3
